name: iambic_research
description: foot survey

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #firebase_auth: ^1.0.1
  #firebase_core: ^1.0.2
  firebase_auth:
  firebase_core:
  camera: #0.5.8+17
  #camera_web:
  path_provider:
  clippy_flutter:
  firebase_storage:
  cloud_firestore:
  firebase_analytics: #^6.2.0
  sensors_plus:
  sensors:
  hexcolor:
  carousel_pro:
  flutter_fadein:
  dotted_line:
  form_field_validator:
  image:
  sa_v1_migration:
  firebase_image:
  delayed_display:
  google_sign_in:
  xfile:
  splashscreen:
  pin_code_fields: ^6.0.1
  video_player: #'>=0.10.11+1 <2.0.0'
  video_player_web:
  video_compress:
  flutter_email_sender:
  url_launcher:
  #device_info:
  exif:
  google_fonts:
  js:
  flutter_dash: ^0.0.1
  shared_preferences:
  #just_audio:
  image_picker:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  #microphone: ^0.1.0
  flutter_rating_bar: ^4.0.0
  device_info_plus: ^3.2.2
  #webview_flutter: ^2.0.13
  #camera_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/logo.png
      - assets/images/Z1ABC.png
      - assets/images/Z1A.png
      - assets/images/Z1B.png
      - assets/images/Z1C.png
      - assets/images/bg.png
      - assets/images/bgT0.png
      - assets/images/icon_setup1_paper.png
      - assets/images/icon_setup2_lighting.png
      - assets/images/icon_setup3_surface.png
      - assets/images/icon_setup4_barefeet.png
      - assets/images/screen.png
      - assets/images/logo_white.png
      - assets/images/icon_tap.png
      - assets/images/icon_connect_email.png
      - assets/images/icon_connect_fb.png
      - assets/images/icon_connect_google.png
      - assets/images/bg_facets_gray.png
      - assets/images/icon_home_1fitprofile.png
      - assets/images/icon_home_2scan_v1.png
      - assets/images/icon_home_3shop_v1.png
      - assets/images/icon_home_4faq_v1.png
      - assets/images/bg_scan_v1.png
      - assets/images/Phone_Icon.png
      - assets/images/Icon_Engage.png
      - assets/images/Icon_Cinderella.png
      - assets/images/Icon_ETA.png
      - assets/images/Icon_Tape.png
      - assets/images/Icon_Rotate.png
      - assets/images/Icon_Lock.png
      - assets/images/Icon_Orientation.png
      - assets/images/our_science_2.png
      - assets/images/T0B_Cinderella.png
      - assets/images/Icon_Pen.png
      - assets/images/T2A_Trace.png
      - assets/images/T2B_Scan.png
      - assets/images/T4A.png
      - assets/images/T4D.png
      - assets/images/T5A.png
      - assets/images/T5A_T7B.png
      - assets/images/T5AM_T7BM.png
      - assets/images/Right_Inner_Scan.png
      - assets/images/T5BM.png
      - assets/images/T5B.png
      - assets/images/T5B_ios.png
      - assets/images/T5C_ios.png
      - assets/images/T7C_ios.png
      - assets/images/T7D_ios.png
      - assets/images/T5C.png
      - assets/images/T5CM.png
      - assets/images/T5D.png
      - assets/images/T5D_T7E.png
      - assets/images/T5DM.png
      - assets/images/T7A.png
      - assets/images/T7C.png
      - assets/images/S4C.png
      - assets/images/1_SnappingPictures.gif
      - assets/images/2_TracingFoot.gif
      - assets/images/3_GettingReady.gif
      - assets/images/TopTilt.gif
      - assets/images/5_Side-Tilt.gif
      - assets/images/6_Side-Tilt.gif
      - assets/images/RotateCamera.gif
      - assets/images/icon_logout.png
      - assets/videos/iambic_scan_left.mp4
      - assets/videos/iambic_scan_right.mp4
      - assets/videos/videoscan_instructions_v2.mp4
      - assets/images/V2I_V3B.png
      - assets/images/Empty_Circle.png
      - assets/images/Full_Circle.png
      - assets/images/iOS_5_OuterR.gif
      - assets/images/iOS_5_OuterL.gif
      - assets/images/iOS_4_InnerR.gif
      - assets/images/iOS_4_InnerL.gif
      - assets/images/iOS_3_Top.gif
      - assets/images/2_TwoSheetsSetup.gif
      - assets/images/heel_alignment.png
      - assets/images/HeelAlignment.gif
      - assets/images/S1DM.png
      - assets/images/NSF_logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Barlow
       fonts:
         - asset: assets/fonts/Barlow-Regular.ttf
           weight: 400
         - asset: assets/fonts/Barlow-Bold.ttf
           weight: 700
         - asset: assets/fonts/Barlow-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Barlow-Medium.ttf
           weight: 500
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
